INSERT INTO offre (id,titre,poste,nombre_postes,diplome_requis,experience_min,specialite,langues,missions,competences,mots_cles,date_limite,actif,date_creation) VALUES (1,'(01) Chef de projets Architecte','(01) Chef de projets Architecte',1,'Architecte (Diplôme d’état Marocain ou diplôme privé reconnu par l’Etat ou diplôme étranger',1,'','','o Pilote, coordonne et contrôle la réalisation des projets lancés par l’ADER-FES, dans le respect des
spécifications, des engagements contractuels et dans le respect des orientations de l’ADER-FES ;
o Vérifie la conformité des études architecturales et techniques avec les termes de référence ;
o Assure la maîtrise d’ouvrage des projets et l’interface avec les équipes projets internes ou externe ;
o Rédige des comptes rendus sur l’avancement des travaux.','Techniques :
o Maîtrise du marché de réhabilitation d’aménagement et des techniques de construction ;
o Maîtrise de la réglementation du domaine ;
o Maîtrise des études techniques et urbanistiques ;
o Maîtrise des démarches auprès des différentes administrations pour mener efficacement les projets ;
o Maîtrise de l’exécution des différents travaux par les entreprises et leur suivi.
Comportementales et Managériales :
o Capacité à manager des projets ;
o Capacité à coopérer avec les collègues de son équipe en vue d''atteindre les objectifs communs ;
o Capacité à identifier à son poste de travail des problèmes simples et /ou récurrents et à appliquer les
procédures existantes pour les résoudre.',NULL,'11Décembre 2024',TRUE,'2026-07-29 15:52:27.261629') ON CONFLICT (id) DO NOTHING;
INSERT INTO offre (id,titre,poste,nombre_postes,diplome_requis,experience_min,specialite,langues,missions,competences,mots_cles,date_limite,actif,date_creation) VALUES (2,'(02) Charge de Communication et Marketing Digital','(02) Charge de Communication et Marketing Digital',2,'',0,'','Arabe, Français, Anglais','o Elaborer et mettre en oeuvre la strategie de communication de l''ADER-FES ;
o Gerer les reseaux sociaux et le site web institutionnel de l''agence ;
o Produire des contenus digitaux (articles, videos, infographies) ;
o Assurer la couverture mediatique des evenements organises par l''agence ;
o Concevoir les supports de communication (plaquettes, affiches, newsletters) ;
o Suivre et analyser les indicateurs de performance des campagnes digitales.
Principales Attributions :
o Rediger et diffuser les communiques de presse et actualites de l''agence ;
o Coordonner avec les partenaires medias et institutionnels ;
o Organiser les conferences de presse et evenements de l''agence ;
o Assurer la veille concurrentielle et mediatique ;
o Gerer le budget communication en coordination avec la direction financiere.','',NULL,'',TRUE,'2026-07-29 16:24:53.072371') ON CONFLICT (id) DO NOTHING;
INSERT INTO offre (id,titre,poste,nombre_postes,diplome_requis,experience_min,specialite,langues,missions,competences,mots_cles,date_limite,actif,date_creation) VALUES (3,'CGM','CGM',1,'Master',2,'','','','',NULL,'',TRUE,'2026-08-06 09:54:45.815375') ON CONFLICT (id) DO NOTHING;
INSERT INTO offre (id,titre,poste,nombre_postes,diplome_requis,experience_min,specialite,langues,missions,competences,mots_cles,date_limite,actif,date_creation) VALUES (4,'(04) Assistant(e) Architecte','Assistant Architecte',1,'Licence en Architecture ou Technicien Spécialisé en Bâtiment/Dessin',1,'Architecture','Arabe, Français','Assister l''architecte responsable dans le suivi des projets d''amenagement et de rehabilitation ; Preparer et mettre a jour les plans et documents techniques (AutoCAD) ; Participer aux visites de chantier et rediger les comptes rendus de suivi ; Assurer le classement et l''archivage des dossiers techniques des projets ; Appuyer la coordination avec les entreprises et bureaux d''etudes intervenants.','Techniques :
o Maitrise du logiciel AutoCAD et des outils de dessin technique ;
o Connaissance des normes de construction et d''amenagement urbain ;
o Capacite a lire et interpreter des plans architecturaux ;
o Notions de suivi de chantier et de controle qualite.
Comportementales :
o Rigueur et sens de l''organisation dans le classement des dossiers ;
o Capacite a travailler en equipe avec les architectes et ingenieurs ;
o Bon relationnel avec les entreprises et prestataires.',NULL,'30/09/2026',TRUE,'2026-08-24 14:14:03.212742') ON CONFLICT (id) DO NOTHING;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (1,'YOUSSEF','Alami','youssef.alami@gmail.com','0661234567','(01) Chef de projets Architecte','MASTER','Gestion des entreprises','ENCG',2024,9,0.5382,'Présélectionné',FALSE,NULL,NULL,NULL,'CV_ALAMI_Youssef_CGM.pdf','2026-07-29 15:53:01.530842',1) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (2,'SARA','Benali','sara.benali@gmail.com','0677890123','(01) Chef de projets Architecte','MASTER','Informatique','USMBA',2024,8,0.6738,'Présélectionné',FALSE,NULL,NULL,NULL,'CV_BENALI_Sara_SI.pdf','2026-07-29 15:53:01.615725',1) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (3,'KARIM','Idrissi','karim.idrissi@gmail.com','0654321987','(01) Chef de projets Architecte','TECHNICIEN SPECIALISE','Informatique','ISTA',2024,8,0.3919,'Non retenu',FALSE,NULL,NULL,NULL,'CV_IDRISSI_Karim_Archiviste.pdf','2026-07-29 15:53:01.635498',1) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (4,'AMINE SAGHIRI','Mohammed','SAGHIRIAMINE95@GMAIL.COM','','(01) Chef de projets Architecte','LICENCE','Générale','NEXA Digital School',2024,0,0.1745,'Non retenu',FALSE,NULL,NULL,NULL,'CV_estudiante_de_MAster.pdf','2026-07-29 15:54:11.756685',1) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (5,'BENALI','Leila','mohammed-amine.saghiri.edu@groupe-gema.com','0672345678','CGM','MASTER','Gestion des entreprises','Autre',2024,4,0.85,'Présélectionné',FALSE,NULL,NULL,NULL,'CV_BENALI_Leila.pdf','2026-08-06 09:56:53.964744',3) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (6,'RACHIDI','Omar','aminesaghiri21@gmail.com','0683456789','CGM','MASTER','Finance','ENCG',2024,6,0.85,'Présélectionné',FALSE,NULL,NULL,NULL,'CV_RACHIDI_Omar.pdf','2026-08-06 09:56:54.155957',3) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (7,'TAZI','Mehdi','mohammedamine.saghiri@usmba.ac.ma','0661234567','CGM','MASTER','Finance','ENCG',2024,5,0.85,'Présélectionné',FALSE,NULL,NULL,NULL,'CV_TAZI_Mehdi.pdf','2026-08-06 09:56:54.204548',3) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (8,'BERRADA','Younes','younes.berrada.pro@gmail.com','06 61 11 22 33','Assistant Architecte','MASTER','Génie Civil et Architecture','École Hassania des Travaux Publics',2020,6,0.3413,'Non retenu',FALSE,NULL,'Français, Arabe, Anglais','AutoCAD, Revit, suivi de chantier, réhabilitation, aménagement urbain, études de faisabilité, dimensionnement de structures, lecture de plans architecturaux, coordination entreprises, normes de construction','test_01_younes_berrada.pdf','2026-08-24 14:26:31.120692',4) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (9,'IDRISSI','Salma','salma.idrissi.cv@gmail.com','06 62 22 33 44','Assistant Architecte','TECHNICIEN SPECIALISE','Dessin de Bâtiment','ISTA Fès',2024,1,0.12,'Non retenu',FALSE,NULL,'Français, Arabe, Anglais, Espagnol','AutoCAD, dessin technique, lecture de plans, classement de dossiers, archivage, normes de construction','test_02_salma_idrissi.pdf','2026-08-24 14:26:35.160431',4) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;
INSERT INTO candidat (id,nom,prenom,email,telephone,poste,diplome,specialite,ecole,promotion,experience,score_ia,decision,decision_manuelle,decideur_manuel,langues,competences,cv_filename,date_depot,offre_id) VALUES (10,'OUAZZANI','Karim','karim.ouazzani.pro@gmail.com','06 63 33 44 55','Assistant Architecte','MASTER','Architecture et Urbanisme','École Supérieure d''Architecture de Fès',2022,2,0.3359,'Non retenu',FALSE,NULL,'Français, Arabe, Anglais','AutoCAD, dessin technique, classement de documents, suivi administratif de projets, coordination de projets, gestion de dossiers, contact prestataires, aménagement','test_03_karim_ouazzani.pdf','2026-08-24 14:26:38.780260',4) ON CONFLICT (id) DO UPDATE SET score_ia=EXCLUDED.score_ia,decision=EXCLUDED.decision;